### ISSUE TITLE
Question: Why can't we change Protocol Handlers after pulling recent commits?

### ISSUE THREAD

**Issue by Hoosayin** [F2I-Consulting/fetpapi#12]
Hi Philippe and Team!

I have been using previous version of FETPAPI Client, and we could switch from Own Protocol Handlers to FETPAPI Handlers for Non-blocking and Blocking operations respectively.

I have noticed that the client now only uses FETPAPI Protocol Handlers, and Own Protocol Handler classes are missing for C++ Source (With FESAPI). I manually created those classes after cloning this repo, and when I try to change Protocol Handlers in my custom implemented commands, I get an exception message saying that you can't change some protocol handlers once the session has started. 

I just want to ask, now can we only set protocol handlers for once before creating the session? And if we cannot change "Some Protocol Handlers", which are those?

Looking forward for your reply.

Regards.

**Comment by philippeVerney** [comment]
Hi Hussain,

> I just want to ask, now can we only set protocol handlers for once before creating the session?

Basically yes. Before this change, we had some potential race conditions if you were changing a protocol which would be currently used.
If you still need to have more protocol handlers, please have a look at [AbstractSession.sendWithSpecificHandler](https://github.com/F2I-Consulting/fetpapi/blob/2666154f61d893af70fa32d6de28d31e8da851d8/src/etp/AbstractSession.h#L255) which allows you to indicate a particular (non registered as default one) protocol handlers to be used as answer for a particular sent message.

> And if we cannot change "Some Protocol Handlers", which are those

No limitation, you can change whatever Protocol Handlers.

**Comment by philippeVerney** [comment]
With [AbstractSession.sendWithSpecificHandler](https://github.com/F2I-Consulting/fetpapi/blob/2666154f61d893af70fa32d6de28d31e8da851d8/src/etp/AbstractSession.h#L255), notice that the handler must not be garbaged collected before to be used. I may improve the java part of the code for ensuring that in the future.

**Comment by Hoosayin** [comment]
Thank you so much for this valuable information. I really appreciate.
