### ISSUE TITLE
Unable to Write Data Array with Larger I and J Counts

### ISSUE THREAD

**Issue by Hoosayin** [F2I-Consulting/fetpapi#14]
Hi Philippe!

I hope you are doing well. I am unable to write data array to the store with larger I and J Counts. On hit-and-trial basis, I have tried writing data arrays with the following I and J Counts:

1.	I: 4000 J: 2000 [Failed]
2.	I: 2000 J: 1000 [Failed]
3.	I: 1000 J: 500 [Success]
4.	I: 4 J: 2 [Success]

Seems like data arrays with larger counts are failing to be written to the store. Here’s the code snippet where I am creating a data array: 

![dataarray - 1](https://github.com/F2I-Consulting/fetpapi/assets/47661256/077a4189-ff1f-43cc-b688-9f84b3e4f63a)

When I turn Verbosity on for the session, I am able to see the exception in response:

![Dataarray - 2](https://github.com/F2I-Consulting/fetpapi/assets/47661256/83746865-caf3-4258-8915-cd79e5154df6)

I am using FETPAPI Data Array Handlers. I have tried using AVRO v1.10.2 as well as AVRO v1.9.0 with Boost 1.81 and ZLib v.1.2.13. Also, I am using FESAPI v2.7.1.0. I am not sure why I am getting this error.

Please let me know if this is a bug or if I am doing something wrong here. Awaiting your kind reply.

Regards.

**Comment by Zohaib-Raza** [comment]
hi @philippeVerney 
i am also getting same issue "Cannot Avro-decode message Header": EOF reached on the large data-array

Kindly suggest the solution . 

thanks

**Comment by philippeVerney** [comment]
There is no quick solution.
I am fully booked and must work first for my payings customers first.
A solution would be for the community to provide the fix through a Pull Request.

**Comment by Hoosayin** [comment]
After debugging, I have found that the message size of data array with 2000 ICount and 1000 JCount is exceeding “maxWebSocketMessagePayloadSize” which is 16000000 bytes. Here’s the state in AbstractSession::encode().

![large data array - reason](https://github.com/F2I-Consulting/fetpapi/assets/47661256/ee3e9e5e-e5ec-4b7c-b23e-71449a29ef2f)

Since message size for said array is 16000190, the highlighted “else” part is executed. Reading the comment made me realize that larger messages should be sent in Chunk messages. So I searched for Chunk in ETPMessages File. In FETPAPI, I have found three structures for Chunk messages, one for “Store”, second for “StoreQuery”, and the third for “StoreNotification”. But I haven’t found their usages. So, I referred to “ETP Specification” for more information on Chunk Messages. Here is the excerpt that I found useful:

![To send - Chunks - ETP Spec](https://github.com/F2I-Consulting/fetpapi/assets/47661256/98e8b950-c7eb-4160-933d-fab0dd6bc608)

What I have understood is that a large “DataObject” should be sent in Chunks. In my case, I guess the DataObject is Grid2DRepresentation which has a UUID. I am able to write it to the store. I am facing size issue when writing its ZValues, i.e., the data array, which is written separately to the store. I am not sure if we can use Chunks for writing data arrays too. If so, I am not sure which UUID to use, because I guess a data array does not have its own UUID. Also, while skimming through the specification, I have seen other terms for sending large messages: “Plural Messages”, “Multi-part Messages”, and “Chunks”. I am not sure, which approach to use.

Another option in my mind was to divide the large data array into smaller ones, and write them to the store for a Grid2DRepresentation in multiple patches. I guess, this approach is not correct in terms of domain perspective. However, I haven’t even found a method to write ZValues in multiple patches. There are two public methods for writing Z Values, and both write the values in patch 0.

![Large Array - 3](https://github.com/F2I-Consulting/fetpapi/assets/47661256/f22491a8-fb54-4dd5-9373-f6c3470e934c)

Here, “createArray2dOfExplicitZ()” is private. I wish I could use it outside the class and try writing larger values in multiple patches. 

Your valuable insights will be highly appreciated.

Regards.

**Comment by philippeVerney** [comment]
Nice analysis!

The relevant part of the ETP specifications for putting large array is mainly described in "13.2.1.2 To put one or more data arrays".

The fix should replace https://github.com/F2I-Consulting/fetpapi/blob/main/src/etp/fesapi/FesapiHdfProxy.cpp#L181 which send a single PutDataArrays message.
UUIDs/Uris are not to be changed in the existing code. The fixed code should instead create a PutUninitializedDataArrays (verify the response but this will be hard so it can be done in a second step) and send multiple PutDataSubarrays messages (ideally in a single transaction but this can also be done in a second step if the RDDMS does not require it).

Regards

**Comment by Hoosayin** [comment]
Hi @philippeVerney!
Thanks for your suggestions. I have modified FesapiHDFProxy class locally to accommodate transmission of larger 2D data arrays in multiple putDataSubrrays messages. I can now successfully write/read larger data arrays. I have tested up to 4000 ICount and 4000 JCount.

Here is what I have done:

1. According to the ETP Specification [13.2.1.2: To put one or more data arrays], first I am sending a single putUnintializedDataArray message in which I populate the URI, Path In Resource, datatype, and the Dimensions of the Data array. I am not handling putUninitializedDataArraysResponse, and I am sending the message with sendAndBlock() to ensure that the request message is sent at least.
2. Then, I calculate the byte size of the array. 
3. If it is smaller than the threshold value “maxArraySize_”, which I have set to 4 MB (This can be altered), the data array is sent in a single putDataArrays message, just like it was sent before in FesapiHDFProxy::writeArrayNd(). 
4. If array size is greater than the threshold value, the array is sent in multiple putDataSubarrays messages using “Divide-and-Conquer” paradigm. I have created a template method FesapiHDFProxy::writeSubArray2d() that takes reference to original row-major data array, and keeps on dividing it into halves recursively. This is done by managing “starts” and “counts” vectors that are required for putDataSubarrays messages. The sub array is immediately sent if its size equals or is smaller than the threshold value. This happens in the base condition. Again, I am not handling putDataSubarraysResponse, and I am sending putDataSubarrays messages using sendAndBlock(). 

The template function works for 2D data arrays only for the following primitive types: double, float, int64, int32, short, and byte.
 
Please, let me know your thoughts. 
Regards.

**Comment by philippeVerney** [comment]
Good news!

A Pull Request would help to make a review. But maybe you don't intend to contribute your code.

I don't think there is a need to putUninitializedDataArraysResponse in all cases. If the array is small enough, going straight to putDataArrays would save one message.

FYI, sendAndBlock actually wait for a response. It does not look at which kind of response (error or not) but it actually blocks untill the response is received.

The threshold value, I think, should be set according to maxWebSocketMessagePayloadSize if available at the HDF Proxy scope.

The following can definitely be done in a second/further step :
- I think there is a possibility to better generalize writeSubArray2d by implementing exisiting FesapiHdfProxy ::writeArrayNdSlab instead which should then be called with 2d dimensions in your case..
- By the way, putUninitializedDataArrays should also be implemented in exisiting FesapiHdfProxy ::createArrayNd (and called through this method if needed)

Happy that you could fix your issue and BRAVO for entering in FETPAPI code!!!!

**Comment by Hoosayin** [comment]
Yes, sure. Let me create a Pull Request. :)

**Comment by philippeVerney** [comment]
Fixed in #15
