### ISSUE TITLE
ImportError when following python example code

### ISSUE THREAD

**Issue by harmankaya** [F2I-Consulting/fetpapi#24]
# What are the steps to reproduce this issue?
just trying out the python example code: https://github.com/F2I-Consulting/fetpapi/blob/main/python/example/etp_client_example.py

# What does happen?
i'm getting `ImportError`

# What were you expecting to happen?
Expecting the example code is working.

# Any logs, error output, etc?
```
Traceback (most recent call last):
  File "/example/example.py", line 6, in <module>
    import fetpapi
  File "/usr/local/lib/python3.12/site-packages/fetpapi/__init__.py", line 10, in <module>
    from . import _fetpapi
ImportError: /usr/local/lib/python3.12/site-packages/fetpapi/../fetpapi.libs/libFetpapi-4a1e711e.so.0.3.0.0: undefined symbol: _ZN11Energistics3Etp3v128Protocol9Dataspace13PutDataspaces10protocolIdE
```

# Any other comments?
Not sure if i'm missing anything. this is done in a docker container from python3.12.7-slim.

# What versions of FETPAPI are you using?
0.3.0.0, which i assume is the latest

**Comment by philippeVerney** [comment]
Hi Yusuf,
At a first glance, I think this is only due to issue #25. Can you confirm that this error message is only with mac with M-processors?
If so, I will close this issue and only let #25 opened.

**Comment by harmankaya** [comment]
The error occurs with the x86 Python container on my local mac. I did a simple test on a VM with an x86 architecture and tried a quick test with Python versions 3.8, 3.11, and 3.12. I'm encountering the same error across all versions.

**Comment by philippeVerney** [comment]
Thank you.
Yes, for now, only Windows and Linux python wheels are delivered, not mac (intel or arm).
I close this ticket in favor of #25
